name: PR Comment
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changes
        run: |
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Add PR Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          gh pr comment ${{ github.event.pull_request.number }} --body "### Changes Detected:
          \`\`\`diff
          $DIFF
          \`\`\`"