name: PR Comment and Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changes
        run: |
          CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-status | base64)
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | base64)
          echo "::set-output name=changes::$CHANGES"
          echo "::set-output name=diff::$DIFF"

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Your PR Changes - ${{ github.event.pull_request.title }}
          body: |
            New changes detected in PR #${{ github.event.pull_request.number }}
            
            Changes:
            ${{ fromJSON(steps.changes.outputs.changes) }}
            
            Detailed Diff:
            ${{ fromJSON(steps.changes.outputs.diff) }}
          to: ${{ github.event.pull_request.user.email }}
          from: GitHub Actions

      - name: Add PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            const changes = Buffer.from('${{ steps.changes.outputs.changes }}', 'base64').toString();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Changes Detected:\n\`\`\`\n${changes}\n\`\`\``
            })