name: PR Comment and Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changes
        run: |
          CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-status | tr '\n' ' ')
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ' ')
          echo "CHANGES_OUTPUT<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "DIFF_OUTPUT<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Your PR Changes - ${{ github.event.pull_request.title }}
          body: |
            New changes detected in PR #${{ github.event.pull_request.number }}
            
            Changes:
            ${{ steps.changes.outputs.CHANGES_OUTPUT }}
            
            Detailed Diff:
            ${{ steps.changes.outputs.DIFF_OUTPUT }}
          to: ${{ github.event.pull_request.user.email }}
          from: GitHub Actions

      - name: Add PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Changes Detected:\n\`\`\`diff\n${process.env.CHANGES_OUTPUT}\n\`\`\``
            })