name: PR Comment
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Create PR Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the changes
          CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          # Create comment with proper formatting
          COMMENT="### 📝 Changes in this PR:

          $(git diff --stat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          ### 🔍 Detailed Changes:

          \`\`\`diff
          $CHANGES
          \`\`\`"
          
          # Post comment to PR
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"